image: "postgres:latest"
commands:
  {% if env.POSTGRES_USER and env.POSTGRES_DB %}
  {# When user, password and database setted  #}
  - "pg_dump -h {{ ip }} -U {{ env.POSTGRES_USER }} -d {{ env.POSTGRES_DB }} -f {{ target_dir }}/{{ env.POSTGRES_DB }}.dump"

  {% elif env.POSTGRES_USER and not env.POSTGRES_DB %}
  {# When user, password setted  #}
  - "pg_dump -h {{ ip }} -U {{ env.POSTGRES_USER }} -d {{ env.POSTGRES_USER }} -f {{ target_dir }}/{{ env.POSTGRES_USER }}.dump"

  {% elif not env.POSTGRES_USER and env.POSTGRES_DB %}
  {# When database setted, password #}
  - "pg_dump -h {{ ip }} -U postgres -d {{ env.POSTGRES_DB }} -f {{ target_dir }}/{{ env.POSTGRES_DB }}.dump"

  {% elif not env.POSTGRES_USER and not env.POSTGRES_DB %}
  {# When just root setted #}
  - "pg_dumpall -h {{ ip }} -U postgres --clean -f {{ target_dir }}/all-databases.dump"

  {% endif %}

environments:
  {% if env.POSTGRES_PASSWORD %}
  - PGPASSWORD:{{ env.POSTGRES_PASSWORD}}
  {% endif %}
